### ISSUE TITLE
Token selection problem on Uniswap

### ISSUE THREAD

**Issue by aetheogamousqhi** [scroll-tech/zkevm-specs#60]
The process of adding liquidity to a pool on Uniswap testing the Scroll Alpha Testnet is impaired due to a token selection issue that only allows for the selection of one token instead of the typical two tokens required to create a pool.
Wallet: 0xF822469b3F003B99960942D4B4ebd37D0b66BFBb

**Comment by OrestTa** [comment]
@Turupawn fyi

**Comment by Turupawn** [comment]
Hey @aetheogamousqhi thanks for submitting, can you please move this issue to the Scroll V3 repo:
https://github.com/scroll-tech/uniswap-v3-interface
I will close this and help you there
Cheers!
