### ISSUE TITLE
Inability to create liquidity pool on Uniswap

### ISSUE THREAD

**Issue by acclamationssbj** [scroll-tech/zkevm-specs#61]
The inability to select two tokens when adding a liquidity pool on Uniswap testing the Scroll Alpha Testnet prevents developers from creating functional pools, which significantly impacts the platform's functionality.
Wallet: 0x4bcFC6877b0cAb74C94fff07571Fa6A35023FA67

**Comment by OrestTa** [comment]
@Turupawn fyi

**Comment by Turupawn** [comment]
Hey @acclamationssbj thanks for submitting, can you please move this issue to the Scroll V3 repo:
https://github.com/scroll-tech/uniswap-v3-interface
I will close this and help you there
Cheers!
