### ISSUE TITLE
Error creating pool on Uniswap

### ISSUE THREAD

**Issue by denominatedmhd** [scroll-tech/zkevm-specs#62]
The inability to select two tokens when adding liquidity to a pool on Uniswap testing the Scroll Alpha Testnet results in the creation of incomplete pools that cannot be used effectively.

**Comment by OrestTa** [comment]
@Turupawn

**Comment by Turupawn** [comment]
Hey @denominatedmhd please move this issue to the Scroll V3 repo:
https://github.com/scroll-tech/uniswap-v3-interface
I will close this and help you there
Cheers!
